image: maven

# estágios
stages:
  - build
#  - Testes
  - image


# maven
compilacao:
  stage: build
  before_script:
    - java -version
    - mvn -version
    - cat /etc/*-release
    - ls -la
  script:
    - mvn clean package -DskipTests
    - ls -la target

nova_image:
  image: docker
  stage: image
  before_script:
    - cat /etc/*-release
    - ls -la
  script:
    - docker version


    

