image: maven

# estágios
stages:
  - build
#  - Testes

# maven
compilar:
  stage: build
  before_script:
    - java -version
    - mvn -version
    - cat /etc/*-release
    - ls -la
  script:
    - mvn clean package -DskipTests
    - ls -la target

