image: maven:3-jdk-8

# estágios
stages:
  - build

# maven
compilar:
  stage: build
  before_script:
    - java -version
    - mvn -version
    - cat /etc/*-release
    - ls -la
  script:
    - mvn clean package -DskipTests
    - ls -la target